// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovaBot.Data;

namespace NovaBot.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191103185902_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NovaBot.Models.ConfigurationModel", b =>
                {
                    b.Property<string>("ConfigurationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BotAccessToken")
                        .HasMaxLength(70);

                    b.Property<string>("BotUserId")
                        .HasMaxLength(70);

                    b.Property<string>("ClientId")
                        .HasMaxLength(70);

                    b.Property<string>("ClientSecret")
                        .HasMaxLength(70);

                    b.Property<string>("LastAuthToken")
                        .HasMaxLength(70);

                    b.HasKey("ConfigurationId");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("NovaBot.Models.QuoteModel", b =>
                {
                    b.Property<string>("QuoteId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<DateTimeOffset>("Date");

                    b.Property<long>("Downvotes");

                    b.Property<string>("QuoteVoteUid");

                    b.Property<string>("SnitchId");

                    b.Property<long>("Upvotes");

                    b.Property<string>("UserId");

                    b.HasKey("QuoteId");

                    b.HasIndex("SnitchId");

                    b.HasIndex("UserId");

                    b.ToTable("Quote");
                });

            modelBuilder.Entity("NovaBot.Models.UserModel", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(400);

                    b.Property<string>("ProfilePicture_192")
                        .HasMaxLength(500);

                    b.Property<string>("ProfilePicutre_512")
                        .HasMaxLength(500);

                    b.Property<string>("ProfilePicutre_72")
                        .HasMaxLength(500);

                    b.Property<long>("Ranking");

                    b.Property<string>("RealName")
                        .HasMaxLength(200);

                    b.Property<string>("Salt")
                        .HasMaxLength(100);

                    b.Property<string>("SlackId")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("StatusText")
                        .HasMaxLength(500);

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("NovaBot.Models.VoteModel", b =>
                {
                    b.Property<string>("UserSlackId");

                    b.Property<string>("QuoteVoteUid");

                    b.Property<string>("QuoteId");

                    b.Property<short>("Vote");

                    b.HasKey("UserSlackId", "QuoteVoteUid");

                    b.HasIndex("QuoteId");

                    b.ToTable("VoteModels");
                });

            modelBuilder.Entity("NovaBot.Models.QuoteModel", b =>
                {
                    b.HasOne("NovaBot.Models.UserModel", "Snitch")
                        .WithMany()
                        .HasForeignKey("SnitchId");

                    b.HasOne("NovaBot.Models.UserModel", "User")
                        .WithMany("Quotes")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("NovaBot.Models.VoteModel", b =>
                {
                    b.HasOne("NovaBot.Models.QuoteModel", "Quote")
                        .WithMany("Votes")
                        .HasForeignKey("QuoteId");

                    b.HasOne("NovaBot.Models.UserModel", "User")
                        .WithMany("MyVotes")
                        .HasForeignKey("UserSlackId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
